name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Запуск каждый день в полночь (UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: LingamYoni/ESET-KeyGen
          ref: main

      - name: Add upstream repository
        run: git remote add upstream https://github.com/rzc0d3r/ESET-KeyGen.git

      - name: Fetch upstream repository
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main

      - name: Push changes
        run: |
          git push origin main
